### ISSUE TITLE
Adjustment to Importing the JAR of Your Theme Into Keycloak when using bitnami helm chart

### ISSUE THREAD

**Issue by tripheo0412** [keycloakify/docs.keycloakify.dev#25]
According to 
- [https://github.com/bitnami/charts/issues/15930](https://github.com/bitnami/charts/issues/15930)
- [https://github.com/bitnami/charts/issues/15930#issuecomment-2478437680](https://github.com/bitnami/charts/issues/15930#issuecomment-2478437680)

With bitnami keycloak helm chart version 24.0.5 and up

```
extraVolumeMounts:
  - mountPath: /opt/bitnami/keycloak/providers
    name: empty-dir
    subPath: app-providers-dir
extraVolumes:
  - emptyDir: {}
    name: empty-dir
initContainers: |
  - name: keycloak-plugin
    image: curlimages/curl
    imagePullPolicy: IfNotPresent
    command:
      - sh
    args:
      - -c
      - |
        # Replace USER and PROJECT.    
        curl -L -f -S -o /extensions/keycloakify-starter.jar https://github.com/USER/PROJECT/releases/latest/download/keycloak-theme-for-kc-26-and-up.jar
  
    volumeMounts:
      - name: empty-dir
        mountPath: /emptydir
```
